export declare enum AllocType {
    Calculated = 1,
    Preliminary = 2,
    SellsideCalculatedUsingPreliminary = 3,
    SellsideCalculatedWithoutPreliminary = 4,
    ReadyToBook = 5,
    BuysideReadyToBook = 6,
    WarehouseInstruction = 7,
    RequestToIntermediary = 8,
    Accept = 9,
    Reject = 10,
    AcceptPending = 11,
    IncompleteGroup = 12,
    CompleteGroup = 13,
    ReversalPending = 14,
    ReopenGroup = 15,
    CancelGroup = 16,
    Giveup = 17,
    Takeup = 18,
    RefuseTakeup = 19,
    InitiateReversal = 20,
    Reverse = 21,
    RefuseReversal = 22,
    SubAllocationGiveup = 23,
    ApproveGiveup = 24,
    ApproveTakeup = 25,
    NotionalValueAveragePxGroupAlloc = 26
}
