export declare enum ComplexEventType {
    Capped = 1,
    Trigger = 2,
    KnockInUp = 3,
    KnockInDown = 4,
    KnockOutUp = 5,
    KnockOutDown = 6,
    Underlying = 7,
    ResetBarrier = 8,
    RollingBarrier = 9,
    OneTouch = 10,
    NoTouch = 11,
    DblOneTouch = 12,
    DblNoTouch = 13,
    FXComposite = 14,
    FXQuanto = 15,
    FXCrssCcy = 16,
    StrkSpread = 17,
    ClndrSpread = 18,
    PxObsvtn = 19,
    PassThrough = 20,
    StrkSched = 21,
    EquityValuation = 22,
    DividendValuation = 23
}
