export declare enum CorporateAction {
    ExDividend = "A",
    ExDistribution = "B",
    ExRights = "C",
    New = "D",
    ExInterest = "E",
    CashDividend = "F",
    StockDividend = "G",
    NonIntegerStockSplit = "H",
    ReverseStockSplit = "I",
    StandardIntegerStockSplit = "J",
    PositionConsolidation = "K",
    LiquidationReorganization = "L",
    MergerReorganization = "M",
    RightsOffering = "N",
    ShareholderMeeting = "O",
    Spinoff = "P",
    TenderOffer = "Q",
    Warrant = "R",
    SpecialAction = "S",
    SymbolConversion = "T",
    CUSIP = "U",
    LeapRollover = "V",
    SuccessionEvent = "W"
}
