export declare enum ExecRestatementReason {
    GTCorporateAction = 0,
    GTRenewal = 1,
    VerbalChange = 2,
    RepricingOfOrder = 3,
    BrokerOption = 4,
    PartialDeclineOfOrderQty = 5,
    CancelOnTradingHalt = 6,
    CancelOnSystemFailure = 7,
    Market = 8,
    Canceled = 9,
    WarehouseRecap = 10,
    PegRefresh = 11,
    CancelOnConnectionLoss = 12,
    CancelOnLogout = 13,
    AssignTimePriority = 14,
    CancelledForTradePriceViolation = 15,
    CancelledForCrossImbalance = 16,
    CxldSMP = 17,
    CxldSMPAggressive = 18,
    CxldSMPPassive = 19,
    CxldSMPAggressivePassive = 20,
    Other = 99
}
