export declare enum MatchExceptionElementType {
    AccruedInterest = 1,
    DealPrice = 2,
    TradeDate = 3,
    SettlementDate = 4,
    SideIndicator = 5,
    TradedCurrency = 6,
    AccountID = 7,
    ExecutingBrokerID = 8,
    SettlementCurrencyAndAmount = 9,
    InvestmentManagerID = 10,
    NetAmount = 11,
    PlaceOfSettlement = 12,
    Commissions = 13,
    SecurityIdentifier = 14,
    QualityAllocated = 15,
    Principal = 16,
    Fees = 17,
    Tax = 18
}
