export declare enum OrderRestrictions {
    ProgramTrade = "1",
    IndexArbitrage = "2",
    NonIndexArbitrage = "3",
    CompetingMarketMaker = "4",
    ActingAsMarketMakerOrSpecialistInSecurity = "5",
    ActingAsMarketMakerOrSpecialistInUnderlying = "6",
    ForeignEntity = "7",
    ExternalMarketParticipant = "8",
    ExternalInterConnectedMarketLinkage = "9",
    RisklessArbitrage = "A",
    IssuerHolding = "B",
    IssuePriceStabilization = "C",
    NonAlgorithmic = "D",
    Algorithmic = "E",
    Cross = "F",
    InsiderAccount = "G",
    SignificantShareholder = "H",
    NormalCourseIssuerBid = "I"
}
