export declare enum OwnerType {
    IndividualInvestor = 1,
    PublicCompany = 2,
    PrivateCompany = 3,
    IndividualTrustee = 4,
    CompanyTrustee = 5,
    PensionPlan = 6,
    CustodianUnderGiftsToMinorsAct = 7,
    Trusts = 8,
    Fiduciaries = 9,
    NetworkingSubAccount = 10,
    NonProfitOrganization = 11,
    CorporateBody = 12,
    Nominee = 13,
    InstitutionalCustomer = 14,
    Combined = 15,
    MemberFirmEmployee = 16,
    MarketMakingAccount = 17,
    ProprietaryAccount = 18,
    NonbrokerDealer = 19,
    UnknownBeneficialOwnerType = 20,
    FirmsErrorAccount = 21,
    FirmAgencyAveragePriceAccount = 22
}
