export declare enum PaymentScheduleType {
    Notional = 0,
    CashFlow = 1,
    FXLinkedNotional = 2,
    FixedRate = 3,
    FutureValueNotional = 4,
    KnownAmount = 5,
    FloatingRateMultiplier = 6,
    Spread = 7,
    CapRate = 8,
    FloorRate = 9,
    NonDeliverableSettlPaymentDates = 10,
    NonDeliverableSettlCalculationDates = 11,
    NonDeliverableFXFixingDates = 12,
    SettlPeriodNotnl = 13,
    SettlPeriodPx = 14,
    CalcPeriod = 15,
    DividendAccrualRateMultiplier = 16,
    DividendAccrualRateSpread = 17,
    DividendAccrualCapRate = 18,
    DividendAccrualFloorRate = 19,
    CompoundingRateMultiplier = 20,
    CompoundingRateSpread = 21,
    CompoundingCapRate = 22,
    CompoundingFloorRate = 23
}
