export declare enum PriceType {
    Percentage = 1,
    PerUnit = 2,
    FixedAmount = 3,
    Discount = 4,
    Premium = 5,
    Spread = 6,
    TEDPrice = 7,
    TEDYield = 8,
    Yield = 9,
    FixedCabinetTradePrice = 10,
    VariableCabinetTradePrice = 11,
    PriceSpread = 12,
    ProductTicksInHalves = 13,
    ProductTicksInFourths = 14,
    ProductTicksInEighths = 15,
    ProductTicksInSixteenths = 16,
    ProductTicksInThirtySeconds = 17,
    ProductTicksInSixtyFourths = 18,
    ProductTicksInOneTwentyEighths = 19,
    NormalRateRepresentation = 20,
    InverseRateRepresentation = 21,
    BasisPoints = 22,
    UpfrontPoints = 23,
    InterestRate = 24,
    PercentageNotional = 25
}
