export declare enum QuoteRejectReason {
    UnknownSymbol = 1,
    Exchange = 2,
    QuoteRequestExceedsLimit = 3,
    TooLateToEnter = 4,
    UnknownQuote = 5,
    DuplicateQuote = 6,
    InvalidBid = 7,
    InvalidPrice = 8,
    NotAuthorizedToQuoteSecurity = 9,
    PriceExceedsCurrentPriceBand = 10,
    QuoteLocked = 11,
    InvalidOrUnknownSecurityIssuer = 12,
    InvalidOrUnknownIssuerOfUnderlyingSecurity = 13,
    NotionalValueExceedsThreshold = 14,
    PriceExceedsCurrentPriceBandDepr = 15,
    ReferencePriceNotAvailable = 16,
    InsufficientCreditLimit = 17,
    ExceededClipSizeLimit = 18,
    ExceededMaxNotionalOrderAmt = 19,
    ExceededDV01PV01Limit = 20,
    ExceededCS01Limit = 21,
    UnavailablePriceLiquidity = 22,
    InvalidMissingEntitlements = 23,
    UnknownAccounts = 24,
    Other = 99
}
