export declare enum QuotePriceType {
    Percent = 1,
    PerShare = 2,
    FixedAmount = 3,
    Discount = 4,
    Premium = 5,
    Spread = 6,
    TEDPrice = 7,
    TEDYield = 8,
    YieldSpread = 9,
    Yield = 10,
    PriceSpread = 12,
    ProductTicksInHalves = 13,
    ProductTicksInFourths = 14,
    ProductTicksInEighths = 15,
    ProductTicksInSixteenths = 16,
    ProductTicksInThirtySeconds = 17,
    ProductTicksInSixtyFourths = 18,
    ProductTicksInOneTwentyEighths = 19,
    NormalRateRepresentation = 20,
    InverseRateRepresentation = 21,
    BasisPoints = 22,
    UpFrontPoints = 23,
    InterestRate = 24,
    PercentageOfNotional = 25
}
